name: CD Windows Runner
on:
  push:
    branches: [ PRO ]
jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - name: Deploy to local folder
      - name: Deploy to Nginx
  run: Copy-Item -Path "index.html" -Destination "C:\nginx\html\index.html" -Force